// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9bV6ZOFF8f0vk1CoJPUuzE6GeJmYPX34',
    appId: '1:899202091738:web:332a162ee3fbab7c55b3e3',
    messagingSenderId: '899202091738',
    projectId: 'habit-tracker-8d502',
    authDomain: 'habit-tracker-8d502.firebaseapp.com',
    storageBucket: 'habit-tracker-8d502.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQNeEzmXa0YKivgTsI8zsovFU-YChXmK0',
    appId: '1:899202091738:android:1ae07aef91393f2d55b3e3',
    messagingSenderId: '899202091738',
    projectId: 'habit-tracker-8d502',
    storageBucket: 'habit-tracker-8d502.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAqAhx6y0GnmwrRKtUcfm49uWLtpeOYFM',
    appId: '1:899202091738:ios:7adea842a0476e5a55b3e3',
    messagingSenderId: '899202091738',
    projectId: 'habit-tracker-8d502',
    storageBucket: 'habit-tracker-8d502.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAqAhx6y0GnmwrRKtUcfm49uWLtpeOYFM',
    appId: '1:899202091738:ios:7adea842a0476e5a55b3e3',
    messagingSenderId: '899202091738',
    projectId: 'habit-tracker-8d502',
    storageBucket: 'habit-tracker-8d502.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9bV6ZOFF8f0vk1CoJPUuzE6GeJmYPX34',
    appId: '1:899202091738:web:6a9b1cbf243af19d55b3e3',
    messagingSenderId: '899202091738',
    projectId: 'habit-tracker-8d502',
    authDomain: 'habit-tracker-8d502.firebaseapp.com',
    storageBucket: 'habit-tracker-8d502.firebasestorage.app',
  );
}
